### ISSUE TITLE
Grid field actions not available

### ISSUE THREAD

**Issue by jonom** [unclecheese/silverstripe-mock-dataobjects#10]
Hi UC,

The GridField 'Add Mock Data' form never seems to show up automatically for me - the only way I can get it is to manually add it to a GridField. Is there a trick to this? When I manually add it with `$config->addComponent(new MockDataGenerator());` it shows up above the form but still works fine. Of course I'd rather not do it that way as I have to remove it before I publish the site.

![screen shot 2015-07-30 at 1 54 57 pm](https://cloud.githubusercontent.com/assets/1079425/8994893/e5fe4456-36c2-11e5-8aac-ba14004428c2.png)

![screen shot 2015-07-30 at 1 59 17 pm](https://cloud.githubusercontent.com/assets/1079425/8994941/3568e6b8-36c3-11e5-99a4-18005b865c0e.png)

**Comment by wernerkrauss** [comment]
Seems GridFieldConfig never calls $this->extend('updateConfig') yet? See https://github.com/unclecheese/silverstripe-mock-dataobjects/blob/master/code/extensions/MockDataObjectGridFieldConfig.php#L8

**Comment by jonom** [comment]
Ah you're right! Looks like this feature should be available from 3.2 onwards. @unclecheese do you want me to add a note to the ReadMe to that effect?

**Comment by jonom** [comment]
Wow the necessary change was merged in to master nearly 2 years ago! I sure hope SemVer helps make these types of changes available quicker in future.

**Comment by wernerkrauss** [comment]
Seems it's solved in SS3.2 now.

**Comment by unclecheese** [comment]
That's great news! I've been waiting ages for that PR to be released! Exciting that we'll finally get this without any extra config.
