### ISSUE TITLE
MockDataObject should detect DB before using RAND()

### ISSUE THREAD

**Issue by t3hn0** [unclecheese/silverstripe-mock-dataobjects#18]
MockDataObject should detect database type before it uses RAND() for sort order.

We're using PostgreSQL and this doesn't work if you select "Include relations".

simple function that detects DB name and returns name of random function:

```
    static function get_DB_Rand() {
        if (DB::get_conn() instanceof MSSQLDatabase) {
            return 'RAND()'; // ? is it
        } else if(DB::get_conn() instanceof PostgreSQLDatabase) {
            return 'RANDOM()';
        } else if(DB::get_conn() instanceof MySQLDatabase) {
            return 'RAND()';
        }
    }
```

**Comment by p0lar-bear** [comment]
+1 on this, I use the SQLite3 module during unit testing and my tests die due to this.
